# _02_tensors

## a_tensor_initialization.py

In [1]:
import torch # torch 라이브러리 import

In [2]:
# torch.Tensor class

t1 = torch.Tensor([1, 2, 3], device = 'cpu')
print(t1.dtype) # torch.float32: Tensor로 선언할 경우, 기본 타입은 float32임.
print(t1.device) # cpu
print(t1.requires_grad) # False
print(t1.size()) # torch.Size([3])
print(t1.shape) # torch.Size([3])

t1_cpu = t1.cpu()

print("#" * 50, 1)

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 1


In [3]:
# torch.tensor function

t2 = torch.tensor([1, 2, 3], device = 'cpu')
print(t2.dtype) # torch.int64: tensor로 호출한 경우, 자료형은 int64임.
print(t2.device) # cpu
print(t2.requires_grad) # False
print(t2.size()) # torch.Size([3])
print(t2.shape) # torch.Size([3])

t2_cpu = t2.cpu()

print("#" * 50, 2)

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 2


In [4]:
a1 = torch.tensor(1) # 대괄호 없이 호출할 경우
print(a1)
print(a1.shape, a1.ndim) # dim = 0이다

tensor(1)
torch.Size([]) 0


In [5]:
a2 = torch.tensor([1]) # 대괄호가 한겹 있을 경우
print(a2)
print(a2.shape, a2.ndim) # dim = 1이다

tensor([1])
torch.Size([1]) 1


In [6]:
a3 = torch.tensor([1, 2, 3, 4, 5]) # 대괄호 한 겹에 원소가 5개인 경우
print(a3)
print(a3.shape, a3.ndim) # shape는 torch.Size([5])가 나온다.

tensor([1, 2, 3, 4, 5])
torch.Size([5]) 1


In [7]:
a4 = torch.tensor([[1], [2], [3], [4], [5]]) # 대괄호가 두 겹인 경우
print(a4)
print(a4.shape, a4.ndim) # shape는 torch.Size([5, 1]), dim = 2가 된다.

# 대괄호가 겹쳐진 수에 따라 dim이 결정되고,
# 가장 바깥쪽 대괄호부터 원소의 개수가 shape의 결과가 된다.

tensor([[1],
        [2],
        [3],
        [4],
        [5]])
torch.Size([5, 1]) 2


In [8]:
a5 = torch.tensor([[1, 2], [3, 4], [5, 6]]) 
print(a5)
print(a5.shape, a5.ndim) # shape은 torch.Size([3, 2]), dim = 2가 된다.

tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2]) 2


In [9]:
a6 = torch.tensor([[[1], [2]], [[3], [4]], [[5], [6]]])
print(a6)
print(a6.shape, a6.ndim) # shape은 torch.Size([3, 2, 1]), dim = 3이 된다.

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])
torch.Size([3, 2, 1]) 3


In [10]:
a7 = torch.tensor([[[[1], [2]]], [[[3], [4]]], [[[5], [6]]]])
print(a7)
print(a7.shape, a7.ndim) # shape은 torch.Size([3, 1, 2, 1]), dim = 4가 된다.

tensor([[[[1],
          [2]]],


        [[[3],
          [4]]],


        [[[5],
          [6]]]])
torch.Size([3, 1, 2, 1]) 4


In [11]:
a8 = torch.tensor([[[[1, 2, 3], [2, 3, 4]]], [[[3, 1, 1], [4, 4, 5]]], [[[5, 6, 2], [6, 3, 1]]]])
print(a8)
print(a8.shape, a8.ndim) # shape은 torch.Size([3, 1, 2, 3]), dim = 4가 된다.

tensor([[[[1, 2, 3],
          [2, 3, 4]]],


        [[[3, 1, 1],
          [4, 4, 5]]],


        [[[5, 6, 2],
          [6, 3, 1]]]])
torch.Size([3, 1, 2, 3]) 4


In [12]:
a9 = torch.tensor([
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9)
print(a9.shape, a9.ndim) # shape은 torch.Size([3, 1, 2, 3, 1]), dim = 5가 된다.

tensor([[[[[1],
           [2],
           [3]],

          [[2],
           [3],
           [4]]]],



        [[[[3],
           [1],
           [1]],

          [[4],
           [4],
           [5]]]],



        [[[[5],
           [6],
           [2]],

          [[6],
           [3],
           [1]]]]])
torch.Size([3, 1, 2, 3, 1]) 5


In [13]:
a10 = torch.tensor([[[1, 2, 3, 4, 5]], [[1, 2, 3, 4, 5]], [[1, 2, 3, 4, 5]], [[1, 2, 3, 4, 5]],])
print(a10)
print(a10.shape, a10.ndim) # shape은 torch.Size([4, 1, 5]), dim = 3이 된다.

tensor([[[1, 2, 3, 4, 5]],

        [[1, 2, 3, 4, 5]],

        [[1, 2, 3, 4, 5]],

        [[1, 2, 3, 4, 5]]])
torch.Size([4, 1, 5]) 3


In [14]:
a11 = torch.tensor([
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
]) # 가장 안쪽 차원의 원소의 개수가 3개, 2개로 서로 다르기 때문에 오류가 남.

ValueError: expected sequence of length 3 at dim 3 (got 2)

## b_tensor_initialization_copy.py

In [16]:
import torch
import numpy as np

In [17]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1, t1.dtype) # Tensor로 선언하여 float32로 나온다
print(t2, t2.dtype) # tensor을 호출하여 int64로 나온다
print(t3, t3.dtype) # tensor를 호출한 결과와 같다

# 3가지 경우 전부 deep_copy가 일어난다.

print("#" * 50)

tensor([1., 2., 3.]) torch.float32
tensor([1, 2, 3]) torch.int64
tensor([1, 2, 3]) torch.int64
##################################################


In [18]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4, t4.dtype) # Tensor로 생성하여 float32가 된다.
print(t5, t5.dtype) # tensor를 호출하여 int32가 된다.
print(t6, t6.dtype) # tensor와 같다.

# t4, t5의 경우 deep_copy가 일어났지만, t6의 경우 shallow_copy가 일어난다.

print("#" * 50)

tensor([1., 2., 3.]) torch.float32
tensor([1, 2, 3], dtype=torch.int32) torch.int32
tensor([100,   2,   3], dtype=torch.int32) torch.int32
##################################################


## c_tensor_initialization_constant_values.py

In [19]:
import torch

In [20]:
t1 = torch.ones(size = (5,)) # shape이 torch.Size([5])이고 1로 채워진 tensor 생성
t1_like = torch.ones_like(input = t1) # t1과 같은 shape에 1로 채워진 tensor 생성
print(t1)
print(t1_like)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


In [21]:
t2 = torch.zeros(size = (6,)) # shape이 torch.Size([6])이고 0으로 채워진 tensor 생성
t2_like = torch.zeros_like(input=t2) # t2와 같은 shape에 0으로 채워진 tensor 생성
print(t2)
print(t2_like)

tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])


In [22]:
t3 = torch.empty(size = (4,)) # shape이 torch.Size([4])이고 비어있는 tensor 생성
t3_like = torch.empty_like(input = t3) # t3와 같은 shape에 비어있는 tensor 생성
print(t3)
print(t3_like)

tensor([0.0000e+00, 0.0000e+00, 5.6052e-45, 0.0000e+00])
tensor([8.4490e-39, 1.0194e-38, 8.9082e-39, 8.4490e-39])


In [23]:
t4 = torch.eye(n=3) # 항등행렬(I) 모양의 tensor 생성
print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## d_tensor_initialization_random_values.py

In [24]:
import torch

In [26]:
t1 = torch.randint(low = 10, high = 20, size = (1, 2)) # low와 high사이의 랜덤한 정수값으로 tensor.Shape([1, 2])인 tensor를 생성한다
print(t1)

tensor([[18, 17]])


In [29]:
t2 = torch.rand(size=(1, 3)) # 0 ~ 1 사이의 랜덤한 실수값으로 tensor.Shape([1, 3])의 tensor를 생성한다
print(t2)

tensor([[0.6076, 0.7191, 0.4711]])


In [31]:
t3 = torch.randn(size=(1, 3)) # 정규분포를 따르는 랜덤한 실수값으로 tensor.Shape([1, 3])인 tensor를 생성한다.
print(t3)

tensor([[ 0.7233, -0.2942,  0.1082]])


In [37]:
t4 = torch.normal(mean = 10.0, std = 1.0, size = (3, 2)) # mean(평균), std(표준 편차)인 정규분포 값을 torch.Shape([3, 2])인 tensor로 생성한다.
print(t4)

tensor([[10.2859,  8.1004],
        [ 8.5567,  8.8812],
        [ 9.8399,  8.4224]])


In [39]:
t5 = torch.linspace(start = 0.0, end = 5.0, steps = 3) # start부터 end까지 일정한 간격을 가진 수를 steps개 만큼 tensor로 생성한다.
print(t5)

tensor([0.0000, 2.5000, 5.0000])


In [41]:
t6 = torch.arange(5) # 0 ~ n - 1까지의 수를 tensor로 생성한다
print(t6)

tensor([0, 1, 2, 3, 4])


In [45]:
torch.manual_seed(1729) # 특정 시드값을 이용하여 일정한 랜덤값을 생성한다
random1 = torch.rand(2, 3)
print(random1)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [46]:
random2 = torch.rand(2, 3)
print(random2)

tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [48]:
torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

# random1과 결과가 같은것을 볼 수 있다.

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [50]:
random4 = torch.rand(2, 3)
print(random4)

# random2와 결과가 같은것을 볼 수 있다.

tensor([[0.6128, 0.1519, 0.0453],
        [0.5035, 0.9978, 0.3884]])


## e_tensor_type_conversion.py

In [51]:
import torch

In [53]:
a = torch.ones((2, 3)) # 그냥 아무것도 없이 생성하면 float32로 생성된다
print(a.dtype)

torch.float32


In [57]:
b = torch.ones((2, 3), dtype=torch.int16) # dtype을 torch.int16으로 설정하여 torch.int16으로 생성된다.
print(b)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [58]:
c = torch.rand((2, 3), dtype=torch.float64) * 2 # dtype을 torch.float64로 하여 생성하였고, 생성된 후 각 값에 2를 곱하였다.
print(c)

tensor([[1.1241, 1.1208, 1.1669],
        [1.8328, 0.0212, 1.8497]], dtype=torch.float64)


In [60]:
d = b.to(torch.int32) # b tensor의 dtype을 torch.int16에서 torch.int32로 변환하여 새로운 d tensor를 생성한다
print(d)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [62]:
double_d = torch.ones(10, 2, dtype=torch.double) # torch.float64로 생성하는 방법 1
short_e = torch.tensor([[1, 2]], dtype=torch.short) # torch.int16으로 생성하는 방법 1
print(double_d)
print(short_e)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[1, 2]], dtype=torch.int16)


In [64]:
double_d = torch.zeros(10, 2).double() # float64로 생성하는 방법 2
short_e = torch.ones(10, 2).short() # int16으로 생성하는 방법 2
print(double_d)
print(short_e)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)


In [66]:
double_d = torch.zeros(10, 2).to(torch.double) # float64로 생성하는 방법 3
short_e = torch.ones(10, 2).to(dtype=torch.short) # int16으로 생성하는 방법 3
print(double_d)
print(short_e)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)


In [68]:
double_d = torch.zeros(10, 2).type(torch.double) # float64로 생성하는 방법 4
short_e = torch.ones(10, 2).type(dtype=torch.short) # int16으로 생성하는 방법 4
print(double_d)
print(short_e)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)


In [71]:
double_f = torch.rand(5, dtype=torch.double) # float64
short_g = double_f.to(torch.short) # int16
print((double_f * short_g).dtype) # 둘을 곱하면 float64로 나온다

torch.float64


## f_tensor_operations.py

In [72]:
import torch

In [76]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2) # 덧셈 연산 함수
t4 = t1 + t2 # 덧셈 연산자

print(t3)
print(t4)

# 같은 결과가 나온다

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [77]:
t5 = torch.sub(t1, t2) # 뺄셈 연산 함수
t6 = t1 - t2 # 뺄셈 연산자

print(t5)
print(t6)

# 같은 결과가 나온다

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [79]:
t7 = torch.mul(t1, t2) # 곱셈 연산 함수
t8 = t1 * t2 # 곱셈 연산자

print(t7)
print(t8)

# 같은 결과가 나온다

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [82]:
t9 = torch.div(t1, t2) # 나눗셈 연산 함수
t10 = t1 / t2 # 나눗셈 연산자

print(t9)
print(t10)

# 같은 결과가 나온다

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


## g_tensor_operations_mm.py

In [83]:
import torch

In [85]:
 t1 = torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1])) # 두 텐서(1D)의 도트곱을 계산한다
print(t1, t1.size())

tensor(7) torch.Size([])


In [89]:
t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3) # 두 텐서의 행렬곱을 수행한다.
print(t4, t4.size())

tensor([[ 0.5501, -0.6629],
        [ 0.3718, -0.4697]]) torch.Size([2, 2])


In [91]:
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6) # 두 텐서의 배치행렬곱을 수행한다.
print(t7, t7.size())

tensor([[[-1.1995e+00,  3.3228e-01,  2.3784e+00, -9.0267e-01, -6.2310e-01],
         [-4.9171e+00,  3.6110e+00,  3.6119e+00,  3.0757e+00, -2.3181e+00],
         [-5.6531e-03,  1.8100e+00, -9.0880e-01,  5.4464e-01, -9.3912e-01]],

        [[-7.1170e-01, -5.0107e+00,  2.9406e+00,  6.4434e-01, -1.5403e+00],
         [-7.1455e-01, -1.3942e+00, -5.9811e-01,  3.8066e+00,  1.8539e+00],
         [-4.1797e+00, -3.7538e+00, -8.0702e-01,  9.7789e-02,  1.3889e+00]],

        [[-5.6938e-01, -2.5808e-01, -4.6690e-01,  1.0613e-01,  8.1542e-01],
         [ 1.8829e+00,  1.3182e+00, -6.9806e-02,  6.4918e-01,  8.4708e-01],
         [ 4.2289e-01,  2.0017e+00,  1.3828e-01,  2.3985e-01,  2.3539e+00]],

        [[ 3.4003e+00,  1.6936e+00, -3.3164e+00, -9.2828e-01, -9.7569e-01],
         [-1.1326e+00, -1.5087e+00,  2.7934e+00, -4.6283e-01,  7.6316e-01],
         [-6.9533e-01, -5.8640e-01,  2.8724e+00,  8.0673e-01, -6.7800e-02]],

        [[-1.1608e+00, -3.7923e-01, -1.0090e-01,  5.7561e-02,  1.9729e-01],
    

## h_tensor_operations_matmul.py

In [93]:
import torch

In [96]:
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size()) #  두 tesnor의 행렬곱을 실행한다. broadcasting을 지원한다.

torch.Size([])


In [97]:
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size()) # 두 tensor의 broadcasted dot product를 실행한다.

torch.Size([3])


In [98]:
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size()) # 두 tensor의 broadcasted dot product를 실행한다.

torch.Size([10, 3])


In [99]:
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size()) # 두 tensor의 batched matrix multiplication을 실행한다.

torch.Size([10, 3, 5])


In [100]:
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size()) # 두 tensor의 multiplication을 실행한다. batch와 broadcast 둘 다 지원한다.

torch.Size([10, 3, 5])


## i_tensor_broadcasting.py

In [101]:
import torch

In [103]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2) # tensor에 상수를 곱하면 자동으로 broadcast된다.

tensor([2., 4., 6.])


In [105]:
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4) # tensor에 더 작은 tensor를 연산하면 자동으로 broadcast된다.

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [107]:
t5 = torch.tensor([[1.,2.], [3.,4.]])
print(t5 + 2.0) # t5.add(2.0)
print(t5 - 2.0) # t5.sub(2.0)
print(t5 * 2.0) # t5.mul(2.0)
print(t5 / 2.0) # t5.div(2.0)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [112]:
def normalize(x):
    return x / 255

In [114]:
t6 = torch.randn(3, 28, 28)
print(normalize(t6).size()) # 원래의 shape을 유지하며, 연산만 된다.

torch.Size([3, 28, 28])


In [116]:
t7 = torch.tensor([[1, 2], [0, 3]])
t8 = torch.tensor([[3, 1]])
t9 = torch.tensor([[5], [2]])
t10 = torch.tensor([7])
print(t7 + t8)
print(t7 + t9)
print(t8 + t9)
print(t7 + t10)

# 더 큰 shape을 가진 tensor의 shape으로 broadcasting 된다.

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [119]:
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)
print(t12.shape) # t12가 t11보다 작으므로 t11의 shape으로 broadcasting된다

torch.Size([4, 3, 2])


In [121]:
t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)
print(t14.shape) # t14가 t13보다 작으므로 t13의 shape으로 broadcasting된다

torch.Size([4, 3, 2])


In [123]:
t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)
print(t16.shape) # t16이 t15보다 작으므로 t15의 shape으로 broadcasting된다

torch.Size([4, 3, 2])


In [125]:
t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)
print((t17 + t18).size()) # t18이 t17보다 작으므로 t17의 shape으로 broadcasting된다

torch.Size([5, 3, 4, 1])


In [127]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size()) # t19의 두번째 차원보다 t20의 첫 번째 차원이 더 크기 때문에, 각 dim의 크기가 더 큰 쪽으로 broadcasting된다.

torch.Size([5, 3, 4, 1])


In [129]:
t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())

torch.Size([3, 1, 7])


In [130]:
t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())

torch.Size([3, 3, 3])


In [133]:
t25 = torch.empty(5, 2, 4, 1)
t26 = torch.empty(3, 1, 1)
print((t25 + t26).size()) # broadcasting한 경우 t26의 shape이 (5, 3, 1, 1)이 되면서 t25의 두번째 차원인 2보다 t26의 두 번째 차원인 3이 더 큰 값을 갖게 되기 때문에 broadcasting이 불가능하다.

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [134]:
t27 = torch.ones(4) * 5
print(t27)

tensor([5., 5., 5., 5.])


In [135]:
t28 = torch.pow(t27, 2)
print(t28)

tensor([25., 25., 25., 25.])


In [136]:
exp = torch.arange(1., 5.)
a = torch.arange(1., 5.)
t29 = torch.pow(a, exp)
print(t29)

tensor([  1.,   4.,  27., 256.])


## j_tensor_indexing_slicing.py

In [137]:
import torch

In [139]:
x = torch.tensor(
[[0, 1, 2, 3, 4],
[5, 6, 7, 8, 9],
[10, 11, 12, 13, 14]]
)

In [141]:
print(x[1]) # x의 1번 인덱스 접근
print(x[:, 1]) # x의 모든 인덱스의 1번 인덱스 접근
print(x[1, 2]) # x의 1번 인덱스의 2번 인덱스 접근
print(x[:, -1]) # x의 모든 인덱스의 가장 마지막 인덱스 접근

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [143]:
print(x[1:]) # x의 1번 인덱스부터 마지막 인덱스까지 접근
print(x[1:, 3:]) # x의 1번 인덱스부터 마지막 인덱스의 3번인덱스부터 마지막 인덱스 까지 접근

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [145]:
y = torch.zeros((6, 6))

In [147]:
y[1:4, 2] = 1 # y의 1번 인덱스부터 3번 인덱스의 2번 인덱스에 1을 대입한다.
print(y)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [150]:
print(y[1:4, 1:4]) # y의 1번 인덱스부터 3번 인덱스의 1번 인덱스부터 3번 인덱스에 접근한다.

tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [152]:
z = torch.tensor(
[[1, 2, 3, 4],
[2, 3, 4, 5],
[5, 6, 7, 8]]
)

In [154]:
print(z[:2]) # z의 맨 첫 인덱스부터 1번 인덱스까지 접근한다
print(z[1:, 1:3]) # z의 1번 인덱스부터 마지막 인덱스의 1번 인덱스부터 2번 인덱스에 접근한다
print(z[:, 1:]) # z의 모든 인덱스의 1번 인덱스부터 마지막 인덱스까지 접근한다.

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])


In [156]:
z[1:, 1:3] = 0 # z의 1번 인덱스부터 마지막 인덱스의 1번 인덱스부터 2번 인덱스에 0을 대입한다.
print(z)

tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


## k_tensor_reshaping.py

In [157]:
import torch

In [159]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2) # 변환하려는 텐서의 실제 메모리 위치가 이용됨
t3 = t1.reshape(1, 6) # 완전히 모양을 바꿔줌

print(t2)
print(t3)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])


In [161]:
t4 = torch.arange(8).view(2, 4) # shape이 (1, 8)에서 (2, 4)로 변함
t5 = torch.arange(6).view(2, 3) # shape이 (1, 6)에서 (2, 3)으로 변함

print(t4)
print(t5)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [164]:
t6 = torch.tensor([[[1], [2], [3]]])
t7 = t6.squeeze() # 모든 차원을 지우고 1로 만든다
t8 = t6.squeeze(0) # 해당 인덱스의 차원을 지운다

print(t7)
print(t8)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


In [167]:
t9 = torch.tensor([1, 2, 3])
t10 = t9.unsqueeze(1) # 1번 인덱스에 새로운 차원을 만든다

print(t10)

tensor([[1],
        [2],
        [3]])


In [170]:
t11 = torch.tensor(
[[1, 2, 3],
[4, 5, 6]]
)
t12 = t11.unsqueeze(1) # shape이 (2, 1, 3)이 된다

print(t12, t12.shape)

tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [171]:
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t14 = t13.flatten() # 1개의 차원으로 만든다.

print(t14)

tensor([1, 2, 3, 4, 5, 6])


In [173]:
t15 = torch.tensor([[[1, 2],
                    [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)
t17 = torch.flatten(t15, start_dim = 1) # 1번째 차원부터 flatten을 진행한다

print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [175]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)
print(torch.permute(t18, (2, 0, 1)).size()) # t18의 dim을 주어진 인덱스 순으로 재배치한다.

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


In [177]:
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t20 = torch.permute(t19, dims=(0, 1)) # 0번 dim과 1번 dim을 순서배로 배치한다
t21 = torch.permute(t19, dims=(1, 0)) # 0번 dim과 1번 dim을 역순으로 배치한다

print(t20) # shape = (2, 3)
print(t21) # shape = (3, 2)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [179]:
t22 = torch.transpose(t19, 0, 1) # tensor의 해당 dim을 교환한다.
print(t22)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [181]:
t23 = torch.t(t19) # transpose와 동일하다
print(t23)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


## i_tensor_concat.py

In [182]:
import torch

In [186]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])
t4 = torch.cat([t1, t2, t3], dim = 1) # 1번 dim 방향으로 텐서를 쌓아올린다.

print(t4.shape)

torch.Size([2, 6, 3])


In [188]:
t5 = torch.arange(0, 3) # [0, 1, 2]
t6 = torch.arange(3, 8) # [3, 4, 5, 6, 7]
t7 = torch.cat((t5, t6), dim = 0) # 0번 dim 방향으로 텐서를 쌓아올린다.

print(t7.shape)
print(t7)

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [191]:
t8 = torch.arange(0, 6).reshape(2, 3)
t9 = torch.arange(6, 12).reshape(2, 3)
t10 = torch.cat((t8, t9), dim = 0) # 0번 dim 방향으로 텐서를 쌓아올린다.

print(t10.size())
print(t10)

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [193]:
t11 = torch.cat((t8, t9), dim = 1) # 1번 dim 방향으로 텐서를 쌓아올린다.
print(t11.size())
print(t11)

torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [195]:
t12 = torch.arange(0, 6).reshape(2, 3)
t13 = torch.arange(6, 12).reshape(2, 3)
t14 = torch.arange(12, 18).reshape(2, 3)
t15 = torch.cat((t12, t13, t14), dim = 0) # 0번 dim 방향으로 텐서를 쌓아올린다.

print(t15.size())
print(t15)

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])


In [197]:
t16 = torch.cat((t12, t13, t14), dim = 1)
print(t16.size())
print(t16)

torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [199]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)
t18 = torch.arange(6, 12).reshape(1, 2, 3)
t19 = torch.cat((t17, t18), dim = 0)
t20 = torch.cat((t17, t18), dim = 0)
t21 = torch.cat((t17, t18), dim = 0)

print(t19.size())
print(t19)

print(t20.size())
print(t20)

print(t21.size())
print(t21)

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])


## m_tensor_stacking.py

In [200]:
import torch

In [202]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])
t3 = torch.stack([t1, t2], dim = 0) # 0번째에 새로운 dim을 만들어 새로운 dim에서 차곡차곡 쌓아올린다. 두 tensor의 shape이 같아야한다.
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)

print(t3.shape, t3.equal(t4))

torch.Size([2, 2, 3]) True


In [204]:
t5 = torch.stack([t1, t2], dim = 1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

torch.Size([2, 2, 3]) True


In [206]:
t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

torch.Size([2, 3, 2]) True


In [208]:
t9 = torch.arange(0, 3)
t10 = torch.arange(3, 6)
print(t9.size(), t10.size())

torch.Size([3]) torch.Size([3])


In [210]:
t11 = torch.stack((t9, t10), dim = 0)
print(t11.size())
print(t11)

torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [212]:
t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))

True


In [213]:
t13 = torch.stack((t9, t10), dim=1)
print(t13.size())
print(t13)

torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [214]:
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim = 1)
print(t13.equal(t14))

True


## n_tensor_vstack_hstack.py

In [215]:
import torch

In [217]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2)) # tensor를 세로로(행 단위로) 쌓아올린다.
print(t3)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [219]:
t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5)) # tensor를 세로로 쌓아올린다

print(t6)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [220]:
t7 = torch.tensor([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)

torch.Size([2, 2, 3])


In [221]:
t8 = torch.tensor([
    [[13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)

torch.Size([2, 2, 3])


In [222]:
t9 = torch.vstack([t7, t8])
print(t9)
print(t9.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
torch.Size([4, 2, 3])


In [224]:
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11)) # tensor를 가로로(열 단위로) 쌓아올린다.
print(t12)

tensor([1, 2, 3, 4, 5, 6])


In [226]:
t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]]) # tensor를 가로로 쌓아올린다.
t15 = torch.hstack((t13, t14))
print(t15)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [227]:
t16 = torch.tensor([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)

torch.Size([2, 2, 3])


In [228]:
t17 = torch.tensor([
    [[13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24]]
])
print(t17)

tensor([[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


In [230]:
t18 = torch.hstack([t16, t17]) # 열 단위로 쌓인다.
print(t18)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


#### 기술 고찰

```python
pycharm IDE와 jupyter notebook을 잘 사용하지 않았어서 처음 실습할 때, 실습환경 설정이나 코드 실행 등 여러 부분에서 불편하고 익숙하지 않았었는데, 교수님의 조언대로 단축키를 외우고 활용하며 사용해보니 굉장히 편하게 코딩할 수 있었다.
```

#### 숙제 후기

```python
tensor의 기초부터 모든 기능에 대한 예제가 나와있고, 이를 하나하나 따라하며 공부할 수 있어서 좋았다.

비슷한 기능이라도 수업시간에 교수님께서 자세히 설명해주셔서 차이점을 공부하는데 어렵지 않았다.
```