***
***
# <center>Script Programming</center>

## <center>Final Exam</center>

#### <center>2022.12.16</center>
***
***

- 제출 형식
  * 평소 퀴즈 제출 방식과 같음(colab url)
- 배점
  * 총 5문항 문항당 20점 (총 100점)

In [65]:
'''이름과 학번을 입력하시오.'''
name = ?
id = ?
print("이름: {}\n학번: {}".format(name, id))

이름: 홍길동
학번: 123


### Q1

함수에 yield 문이 있다는 것만으로도 generator의 역할을 할 수 있다.

일반 함수와 달리 generator는 반복에 대한 응답으로만 실행된다.

아래 main에서 사용되는 dountdown 함수의 몸체(body)를 완성하시오.


In [ ]:
def countdown(n):
  ...

In [ ]:
# main
c = countdown(3)
print(c)
print(next(c))
print(next(c))
print(next(c))
print(next(c))

<generator object countdown at 0x7f5c72658040>
3
2
1
End


StopIteration: ignored

#### Q1 출력결과

<img src = "https://drive.google.com/uc?id=1nDF5xfPrn5MiOBxQsLAnGLp5LqAr2ZVB">

### Q2

일반적으로 내부 변수는 외부 세계에 완전히 숨겨져 있다.

그러나 접근자 함수(get_n)를 작성하고 액세스를 제공할 수 있다.

sample 함수 내부의 비어있는 부분을 채우시오.

In [ ]:
def sample():
  n=0
  def func():
    ...
    
  def get_n():
    ...
    
  def set_n(value):
    nonlocal n
    ...
  
  # Attach as function attributes
  func.get_n = get_n
  func.set_n = set_n
  return func

In [ ]:
# main
f = sample()
f()

f.set_n(10)
f()

f.get_n()

n= 0
n= 10


10

#### Q2 출력결과

<img src = "https://drive.google.com/uc?id=1nFm4RsdDRTdYKlAlwAEmK9lCMJUWwrQk">

### Q3

인스턴스의 문자열 표현을 변경하기위해 __str__() 및 __repr__() 함수를 정의하시오.

In [ ]:
class Pair:
  def __init__(self, x, y):
    self.x = x
    self.y = y

  def __repr__(self):
    ...

  def __str__(self):
    ...

In [ ]:
# main
p = Pair(3, 4)
p #

Pair(3, 4)

In [ ]:
# main
print(p)

(3, 4)


#### Q3 출력결과

<img src = "https://drive.google.com/uc?id=1nKA2bGbG5-5_v3DCLt6M3mF4HNMNKhbV">

### Q4

프로그램에서 thread를 사용하고 공유 변수의 경합 상태를 피하기 위해 코드의 critical section을 잠그려한다.

공유 변수를 여러 스레드에서 안전하게 사용하려면 다음과 같이 스레딩 라이브러리에서 Lock 객체를 사용해야한다.

출력 결과 Counter 객체의 공유 변수 value의 결과는 0이 되어야 한다.

코드의 incr, decr 함수를 완성하시오.

In [50]:
import threading
import time


class Counter:
  def __init__(self, initial_value = 0):
    self.value = initial_value
    self.value_lock = threading.Lock()
    self._start()
  
  def incr(self,delta=1):
    for i in range(100000):
      self.value += delta
      ...
  
  def decr(self,delta=1):
    for i in range(100000):
      self.value -= delta
      ...
  
  def _start(self):
    t1 = threading.Thread(target=self.incr, args=(1,))
    t2 = threading.Thread(target=self.decr, args=(1,))
    t1.start()
    t2.start()
    t1.join()
    t2.join()

In [51]:
# main
counter = Counter()
counter.value

0

#### Q4 출력결과

0

### Q5

### 아래 iris 붓꽃 데이터들은 총 3가지 종류 'setosa', 'versicolor', 'virginica' 붓꽃의 (1) sepal length, (2) sepal width, (3) petal length, (4) petal width를 포함한다.
### 데이터들을 붓꽃 종류별로 평균내어 [평균 (1), 표준편차 (1)], [평균 (2), 표준편차 (2)], [평균 (3), 표준편차 (3)], [평균 (4), 표준편차 (4)] 각각을 구하시오.
- 1) 'setosa'의 [평균 (1), 표준편차 (1)], [평균 (2), 표준편차 (2)], [평균 (3), 표준편차 (3)], [평균 (4), 표준편차 (4)]
- 2) 'versicolor'의 [평균 (1), 표준편차 (1)], [평균 (2), 표준편차 (2)], [평균 (3), 표준편차 (3)], [평균 (4), 표준편차 (4)]
- 3) 'virginica'의 [평균 (1), 표준편차 (1)], [평균 (2), 표준편차 (2)], [평균 (3), 표준편차 (3)], [평균 (4), 표준편차 (4)]

In [52]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

iris = load_iris()

In [53]:
i = 0
for k, v in iris.items():
  print(k, v)
  i += 1
  if i == 2:
    break

data [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3

In [61]:
import numpy as np


data = np.array(iris['data'])
target = np.array(iris['target'])
...

In [62]:
print(np.concatenate([setosa, versicolor, virginica], axis=0).reshape(3, 4, 2))

[[[5.006      0.34894699]
  [3.428      0.37525458]
  [1.462      0.17191859]
  [0.246      0.10432641]]

 [[5.936      0.51098337]
  [2.77       0.31064449]
  [4.26       0.46518813]
  [1.326      0.19576517]]

 [[6.588      0.62948868]
  [2.974      0.31925538]
  [5.552      0.54634787]
  [2.026      0.27188968]]]


#### Q5 출력결과

<img src = "https://drive.google.com/uc?id=1nOYw27C3kUwlBS2Z8DYpleARzMKBH1Gx">